base_image: "anyscale/ray-ml:pinned-nightly-py37"
env_vars: {"RAY_BACKEND_LOG_LEVEL": "debug"}
debian_packages: []

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - pip uninstall -y ray
  - pip install -U --user https://s3-us-west-2.amazonaws.com/ray-wheels/master/5eb51c8b26f92f1269d8345c8f81d17f5bf563f6/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  - pip3 install sklearn
  - echo {{env["DATESTAMP"]}}
